# Generated by Django 4.1.1 on 2022-09-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slave',
            fields=[
                ('unique_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('mains_val', models.BooleanField(default=False)),
                ('dim_val', models.IntegerField(choices=[(25, '25'), (50, '50'), (75, '75'), (100, '100')], default=25)),
                ('temperature', models.FloatField(null=True)),
                ('current', models.FloatField(null=True)),
            ],
        ),
    ]
