# Generated by Django 4.1.1 on 2022-10-19 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_alter_slave_dim_val'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.IntegerField(primary_key=True, serialize=False)),
                ('schedule_name', models.CharField(max_length=100)),
                ('current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('intensity', models.IntegerField(choices=[(0, '0'), (25, '25'), (50, '50'), (75, '75'), (100, '100')], default=25)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node.schedule')),
            ],
        ),
    ]
