# Generated by Django 4.1.1 on 2022-10-19 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0004_schedule_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='current',
            new_name='currently_active',
        ),
    ]
