# Generated by Django 4.1.2 on 2022-10-20 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0005_rename_current_schedule_currently_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimeStamp', models.DateTimeField(auto_now_add=True)),
                ('temperatureValue', models.FloatField()),
                ('SlaveId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node.slave')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimeStamp', models.DateTimeField(auto_now_add=True)),
                ('currentValue', models.FloatField()),
                ('SlaveId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node.slave')),
            ],
        ),
    ]
