# Generated by Django 4.1.4 on 2023-02-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0006_temperaturemeasurement_currentmeasurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('toggle', 'Toggle mains switch'), ('dim', 'Perform dimming'), ('current', 'Alert on current value'), ('temperature', 'Alert on temperature value')], max_length=16)),
                ('timestamp', models.DateTimeField()),
                ('success', models.BooleanField()),
                ('is_read', models.BooleanField(default=False)),
                ('message', models.TextField()),
            ],
        ),
    ]
