# Generated by Django 4.1.4 on 2023-03-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='operation_type',
            field=models.CharField(choices=[('toggle', 'Toggle mains switch'), ('dim', 'Perform dimming'), ('current', 'Alert on current value'), ('temperature', 'Alert on temperature value'), ('information', 'Misc like sync with auto interval')], max_length=16),
        ),
    ]
